version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db