version: '3'  

services:  
  nginx:
    image: nginx:latest
    container_name: nginx_001
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src      
      - ./src/static:/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django_001
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn twisted.wsgi -b 0.0.0.0:5000 --log-file -"
    volumes:
      - ./src:/src
      - ./src/static:/static
    depends_on:
      - db
    expose:
      - "5000"
  db:
    image: postgres
    ports:
      - "5432:5432"

